export const mockCars = [
  {
    id: "1",
    name: "BMW",
    consumeFuel: "11.2",
    price: "300",
    rating: "3.2",
    image: require("../assets/images/card-car/car1.png"),
    maxSpeed: "200",
    fuelType: "petrol",
    tankCapacity: "40",
  },
  {
    id: "2",
    name: "AUDI",
    consumeFuel: "11.2",
    price: "240",
    rating: "3.2",
    image: require("../assets/images/card-car/car2.png"),
    maxSpeed: "300",
    fuelType: "petrol",
    tankCapacity: "10",
  },
  {
    id: "4",
    name: "Mersedes",
    consumeFuel: "16.2",
    price: "300",
    rating: "3.2",
    image: require("../assets/images/card-car/car3.png"),
    maxSpeed: "250",
    fuelType: "petrol",
    tankCapacity: "30",
  },
  {
    id: "5",
    name: "Renault",
    consumeFuel: "21.2",
    price: "100",
    rating: "4.2",
    image: require("../assets/images/card-car/car1.png"),
    maxSpeed: "100",
    fuelType: "diesel",
    tankCapacity: "20",
  },
];
